<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.186" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2025-03-11T08:57:17" tests="1" file="cypress\e2e\EXAMPLE\UG-APPLY-ED\ug-apply-ed-c.feature" time="0.184" failures="1">
    <testcase name="An uncaught error was detected outside of a test" time="0.000" classname="An uncaught error was detected outside of a test">
      <failure message="The following error originated from your test code, not from Cypress.

  &gt; Tag expression &quot;\@UTILTEST\&quot; could not be parsed because of syntax error: Illegal escape before &quot;@&quot;.

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure." type="Error"><![CDATA[Error: The following error originated from your test code, not from Cypress.

  > Tag expression "\@UTILTEST\" could not be parsed because of syntax error: Illegal escape before "@".

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
    at tokenize (http://localhost:52119/__cypress/tests?p=cypress\e2e\EXAMPLE\UG-APPLY-ED\ug-apply-ed-c.feature:9834:21)
    at parse (http://localhost:52119/__cypress/tests?p=cypress\e2e\EXAMPLE\UG-APPLY-ED\ug-apply-ed-c.feature:9769:22)
    at createTestFilter (http://localhost:52119/__cypress/tests?p=cypress\e2e\EXAMPLE\UG-APPLY-ED\ug-apply-ed-c.feature:86623:55)
    at createTests2 (http://localhost:52119/__cypress/tests?p=cypress\e2e\EXAMPLE\UG-APPLY-ED\ug-apply-ed-c.feature:86823:28)
    at eval (http://localhost:52119/__cypress/tests?p=cypress\e2e\EXAMPLE\UG-APPLY-ED\ug-apply-ed-c.feature:98803:3)
    at eval (http://localhost:52119/__cypress/tests?p=cypress\e2e\EXAMPLE\UG-APPLY-ED\ug-apply-ed-c.feature:98804:3)
    at eval (<anonymous>)]]></failure>
    </testcase>
  </testsuite>
</testsuites>